# Generated by Django 2.1.4 on 2019-06-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='ClassName',
        ),
    ]
