# Generated by Django 2.1.4 on 2019-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190612_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
