# Generated by Django 2.1.4 on 2019-06-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_classname_published_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='MyformData',
        ),
    ]
