# Generated by Django 2.1.4 on 2019-06-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumber',
            name='Mobile',
            field=models.IntegerField(max_length=12),
        ),
    ]
